# docker-compose.yml
version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booktheflight
    ports:
      - "5454:5432"
    restart: always

  migrator:
    build: .
    container_name: booktheflight-migrator
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go migration
    restart: on-failure

  backend:
    build: .
    container_name: booktheflight-backend
    depends_on:
      - migrator
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: go run main.go
    ports:
      - "8080:8080"
